language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
 - pip install pytest coverage python-coveralls flake8
 - pip install -r requirements.txt

# command to run tests
script:
  - coverage run --source pyplanes -m py.test
  - flake8 pymls

after_success:
- coveralls
